// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs2pDF8PzOy6ZTfbAOhCw1Kh82blmC4Yg',
    appId: '1:286650198866:web:0dac69e5df08e2fb90a88b',
    messagingSenderId: '286650198866',
    projectId: 'kertasinapp',
    authDomain: 'kertasinapp.firebaseapp.com',
    storageBucket: 'kertasinapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE7Me4KgC-MJGw5AvpDiGNhmjhwZWMPAo',
    appId: '1:286650198866:android:d3b38bc2cf591c4a90a88b',
    messagingSenderId: '286650198866',
    projectId: 'kertasinapp',
    storageBucket: 'kertasinapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVdjEpcA7mRWhAluSOX6Hksu07ZDMVCMM',
    appId: '1:286650198866:ios:6de9e5d98e3bfbb590a88b',
    messagingSenderId: '286650198866',
    projectId: 'kertasinapp',
    storageBucket: 'kertasinapp.firebasestorage.app',
    iosBundleId: 'com.example.kertasinapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVdjEpcA7mRWhAluSOX6Hksu07ZDMVCMM',
    appId: '1:286650198866:ios:6de9e5d98e3bfbb590a88b',
    messagingSenderId: '286650198866',
    projectId: 'kertasinapp',
    storageBucket: 'kertasinapp.firebasestorage.app',
    iosBundleId: 'com.example.kertasinapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDs2pDF8PzOy6ZTfbAOhCw1Kh82blmC4Yg',
    appId: '1:286650198866:web:61929707f7e3637a90a88b',
    messagingSenderId: '286650198866',
    projectId: 'kertasinapp',
    authDomain: 'kertasinapp.firebaseapp.com',
    storageBucket: 'kertasinapp.firebasestorage.app',
  );
}
