# ios/Podfile

platform :ios, '12.0'

ENV['FLUTTER_ROOT'] ||= File.expand_path('../flutter', __dir__)
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), __dir__)

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

end
